dynaform/urls.py
from django.conf.urls import url

from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^(?P<lq_id>\d+)/$', views.questionaire_view, name='questionaire'),
    url(r'^formset/(?P<lq_id>\d+)/$', views.formset_view, name='formset'),
    url(r'^multi-formset/(?P<slug>[\w-]+)/$', views.multi_formset_view, name='multi_formset'),
    url(r'^form-to-docx/(?P<slug>[\w-]+)/$', views.form_to_docx, name='form-to-docx'),
    url(r'^form-to-docx/file/(?P<slug>[\w-]+)/(?P<uuid>[\w-]+)/$', views.docx_download_page, name='form-to-docx'), 
    url(r'^upload-templates/$',views.legal_template_upload_view,name="legal templates")
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ftd/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from dynaform import views 
import dynaform.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomeView.as_view(),name='home'),
    url(r'^',include(dynaform.urls)),
]

dynaform/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.text import slugify
import uuid
import os
# Create your models here.

class LegalQuestionaire(models.Model):
	name = models.CharField(max_length=255)
	#def __str__(self):
	#	return self.name

	def __unicode__(self):
		return unicode(self.name)



'''
Field types to include
 - text
 - date
 - number
 - true/false
 - multiple choice field.(this is going to need a separate table? for values)

'''
FIELD_TYPE_CHOICES=(
	(0,'textfield'),
	(1,'charfield'),
	(2,'boolean'),
	(3,'integer'),
	(4,'select'),
	)

class Questions(models.Model):
	questionaire = models.ForeignKey(LegalQuestionaire)
	question_name = models.CharField(max_length=255)
	label = models.CharField(max_length=255)
	field_type = models.IntegerField(choices = FIELD_TYPE_CHOICES)

	#def __str__(self):
	#	return self.label

	def __unicode__(self):
		return unicode(self.label)

class LegalDocuments(models.Model):
	docfile = models.FileField(upload_to='documents/')
	group = models.CharField(max_length=255,default='form_group')
	slug = models.SlugField(default="abc",editable=False)
	unique_id=models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4)

	def filename(self):
		return os.path.basename(self.docfile.name)

	def __unicode__(self):
		return unicode(str(self.group) + " " + str(self.unique_id))

	def save(self):
		super(LegalDocuments, self).save()
		self.slug = slugify(self.group)
		super(LegalDocuments, self).save()

	
class LegalTemplates(models.Model):
	group = models.CharField(max_length=255,default='form_group')
	slug = models.SlugField(default="abc",editable=False)	
	docfile = models.FileField(upload_to='docx-templates/')

	def __unicode__(self):
		return unicode(self.group)

	def save(self):
		super(LegalTemplates, self).save()
		self.slug = slugify(self.group)
		super(LegalTemplates, self).save()

class FormLevelThree(models.Model):
	form = models.ForeignKey(LegalQuestionaire,blank=True,null=True)
	#form = models.ForeignKey(LegalQuestionaire,blank=True,null=True)
	is_formset = models.BooleanField(default=True)
	def __unicode__(self):
		return unicode(self.form)
		
class FormLevelTwo(models.Model):
	form = models.ForeignKey(LegalQuestionaire,blank=True,null=True)
	is_formset = models.BooleanField(default=True)
	child = models.ForeignKey(FormLevelThree,blank=True,null=True)
	def __unicode__(self):
		return unicode(self.form)


class FormLevelOne(models.Model):
	form = models.ForeignKey(LegalQuestionaire,blank=True,null=True)
	is_formset = models.BooleanField(default=True)
	child = models.ForeignKey(FormLevelTwo,blank=True,null=True)
	def __unicode__(self):
		return unicode(self.form)

class FormBaseLevel(models.Model):
	group = models.CharField(max_length=255,default='form_group')
	form = models.ForeignKey(LegalQuestionaire,blank=True,null=True)
	is_formset = models.BooleanField(default=True)
	child = models.ForeignKey(FormLevelOne,blank=True,null=True)
	slug = models.SlugField(default="abc")
	def __unicode__(self):
		return unicode(self.form)

	def save(self):
		super(FormBaseLevel, self).save()
		self.slug = slugify(self.group)
		super(FormBaseLevel, self).save()
		

'''
create the 4 nest levels 
legal questionaire as foreign key
include a parent field
and a child field
as well maybe a ref field to some value in the parent or something.
''' 

dynaform/forms.py
from django import forms 

from .models import LegalQuestionaire,Questions

FIELD_TYPES={
	0:forms.CharField,
	1:forms.CharField,
	2:forms.BooleanField,
	3:forms.IntegerField,
}

class QuestionsForm(forms.Form):


	#this is going to pop out the questionaire id created in the view
	def __init__(self,*args,**kwargs):
		self.questionaire=kwargs.pop('questionaire')
		super(QuestionsForm,self).__init__(*args,**kwargs)
		
		#these are the questions that you can 
		questionaire = LegalQuestionaire.objects.get(pk=self.questionaire)
		questions= Questions.objects.filter(questionaire=questionaire)
		for question in questions:
			#self.fields['custom_%s' % question.label] = forms.CharField(max_length=255) 
			self.fields['%s' % question.question_name] = FIELD_TYPES[question.field_type](label=question.label)

	#this is going to get the questions from the database

	def get_questionaire(self):
		questionaire = LegalQuestionaire.objects.get(pk=self.questionsionaire)
		questions= Questions.objects.filter(questionaire=questionaire)
		return questions

class LegalTemplatesUploadForm(forms.Form):
	docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )

class QuestionsFormNest(forms.Form):


	#this is going to pop out the questionaire id created in the view
	def __init__(self,*args,**kwargs):
		#pop the questionaire id
		self.questionaire=kwargs.pop('questionaire')
		if "parent" in kwargs:
			self.parent = kwargs.pop('parent')
		else:
			self.parent = "None"
		self.is_formset = kwargs.pop('is_formset')

		

		super(QuestionsFormNest,self).__init__(*args,**kwargs)

		#this creates the questions based on the questionaire number
		questionaire = LegalQuestionaire.objects.get(pk=self.questionaire)
		questions= Questions.objects.filter(questionaire=questionaire)
		for question in questions:
			#text areas 
			if question.field_type==0:
				self.fields['%s' % question.question_name] = FIELD_TYPES[question.field_type](label=question.label,widget=forms.Textarea)
			#booleans
			elif question.field_type==2:
				self.fields['%s' % question.question_name] = FIELD_TYPES[question.field_type](label=question.label,widget=forms.RadioSelect(choices= ((True, 'Yes',), (False, 'No',))))
			#all other fields
			else: 
				self.fields['%s' % question.question_name] = FIELD_TYPES[question.field_type](label=question.label)
		
		#this creates some of the management of questions
		self.fields['is_deleted'] = forms.CharField(widget=forms.HiddenInput(),max_length=255,initial=str(False))
		self.fields['parent_name'] = forms.CharField(widget=forms.HiddenInput(),max_length=255,initial=self.parent)
		self.fields['parent_id'] = forms.IntegerField(widget=forms.HiddenInput(),initial=0)
		self.fields['form_name']= forms.CharField(widget=forms.HiddenInput(),max_length=255,initial=questionaire.name)		
		self.fields['form_id'] = forms.IntegerField(widget=forms.HiddenInput(),initial=0)
		self.fields['is_formset'] = forms.CharField(widget=forms.HiddenInput(),initial=str(self.is_formset))
		
	#this is going to get the questions from the database

	def get_questionaire(self):
		questionaire = LegalQuestionaire.objects.get(pk=self.questionsionaire)
		questions= Questions.objects.filter(questionaire=questionaire)
		return questions

dynaform/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from django.views.generic import View
from django.http import Http404
from django.http import HttpResponseRedirect
from django.forms.formsets import formset_factory
from django.core.files import File

from models import LegalQuestionaire,Questions,LegalTemplates
from models import FormBaseLevel, FormLevelOne, FormLevelTwo,FormLevelThree
from models import LegalTemplates, LegalDocuments
from forms import QuestionsForm,LegalTemplatesUploadForm, QuestionsFormNest
import json
import datetime
# Create your views here.
from docxtpl import DocxTemplate

from django.conf import settings



class HomeView(ListView):
	template_name = 'base.html'
	queryset = LegalQuestionaire.objects.all()

def docx_download_page(request,slug,uuid):
	try: 
		doc= LegalDocuments.objects.get(slug=slug,unique_id=uuid)
		
		file_name =  str(doc.filename())
		print file_name
		return render(request, 'dynaform/file.html', {'filename':file_name})

	except LegalDocuments.DoesNotExist:
		raise Http404("Legal document does not exist")	

	return render(request, 'dynaform/file.html', {'filename':file_name})





def form_to_docx(request,slug):

	#an attempt at nested formsets

	formset_list =[]
	try:
		#create the base formset that everything is based off of.
		QuestionsFormset = formset_factory(QuestionsFormNest)

		#get the questionaire list from the group
		questionaire_list = FormBaseLevel.objects.filter(slug=slug)

		#get the template
		template_file = LegalTemplates.objects.filter(slug=slug)

		
		formset_list =[]
		formset_dict = {}
		#create the formsets to access the cleaned data
		if request.method=='POST':
			
			for questionaire in questionaire_list:
				formset_dict['name'] = questionaire.form.name
				formset_dict['data'] = QuestionsFormset(request.POST,form_kwargs={'questionaire':questionaire.form.id,'is_formset':questionaire.is_formset},prefix=questionaire.form.name)  
				formset_dict['parent'] = "None"
				formset_dict['is_formset'] = questionaire.is_formset
				if questionaire.child is not None:
					formset_dict['child'] = str(questionaire.child.form.name)
				else:
					formset_dict['child'] = str(None)
				
				formset_dict['level'] = 0
				
				formset_list.append(formset_dict.copy())
				#set the parent for the child
				parent = questionaire.form.name
				if questionaire.child is not None:
					
					formset_dict['name'] = questionaire.child.form.name
					formset_dict['data'] = QuestionsFormset(request.POST,form_kwargs={'questionaire':questionaire.child.form.id,'parent':parent,'is_formset':questionaire.child.is_formset},prefix=questionaire.child.form.name)
					formset_dict['parent'] = parent 

					formset_dict['is_formset'] = questionaire.child.is_formset
					if questionaire.child.child is not None:
						formset_dict['child'] = str(questionaire.child.child.form.name)
					else:
						formset_dict['child'] = str(None)
					formset_dict['level'] = 1

					parent = questionaire.child.form.name
					formset_list.append(formset_dict.copy())
						
					#this is the child of the child.
					if questionaire.child.child is not None:
					
						formset_dict['name'] = questionaire.child.child.form.name
						formset_dict['data'] = QuestionsFormset(request.POST,form_kwargs={'questionaire':questionaire.child.child.form.id,'parent':parent,'is_formset':questionaire.child.child.is_formset},prefix=questionaire.child.child.form.name) 
						formset_dict['parent'] = parent
						formset_dict['is_formset'] = questionaire.child.child.is_formset
					
						if questionaire.child.child.child is not None:
							formset_dict['child'] = str(questionaire.child.child.child.form.name)
						else:
							formset_dict['child'] = str(None)
						
						formset_dict['level'] = 2
							
						#set for the next level down.
						parent = questionaire.child.child.form.name
						level = formset_dict['level']

						formset_list.append(formset_dict.copy())			
						#this is the child of the child.
						if questionaire.child.child.child is not None:
						
							formset_dict['name'] = questionaire.child.child.child.form.name
							formset_dict['data'] = QuestionsFormset(request.POST,form_kwargs={'questionaire':questionaire.child.child.child.form.id,'parent':parent,'is_formset':questionaire.child.child.child.is_formset},prefix=questionaire.child.child.child.form.name) 
							formset_dict['parent'] = parent
							formset_dict['is_formset'] = questionaire.child.child.child.is_formset
					
							if questionaire.child.child.child is not None:
								formset_dict['child'] = str(questionaire.child.child.child.form.name)
							else:
								formset_dict['child'] = str(None)
							
							formset_dict['level'] = 3
								
							#set for the next level down.
							parent = questionaire.child.child.child.form.name
							level = formset_dict['level']

							formset_list.append(formset_dict.copy())			
					
			#print the clean data to a dict
			cleaned_data = []				
			if_errors = False
			print json.dumps(formset_list[0]['data'].data,sort_keys=True, indent=4)
			for formset in formset_list:
				print ""
				print "check for formset" +str(formset['name'])
				
				#print json.dumps(formset['data'].data,sort_keys=True, indent=4)
				if formset['data'].is_valid():
					print formset['data'].cleaned_data
					cleaned_data = cleaned_data + formset['data'].cleaned_data
					
				else:
					print formset['data'].errors
					if_errors = True
			
			#print "thisis the cleaned data"
			#print the cleaned data out
			print json.dumps(cleaned_data,sort_keys=True, indent=4)
			



			if if_errors ==False:		
				#This can be done in another function
				counter = 0
				length = len(cleaned_data)
				while counter<length:

					data = cleaned_data[counter]

					if data['parent_name']!="None":

						for append_data in cleaned_data:

							cleaned_data,length,counter = format_form_data(append_data,cleaned_data,counter,length)		
					
					else:
						counter = counter + 1

				print cleaned_data
							
				'''
				if data['parent_name']!="None":
					
					for append_data in cleaned_data:
						
						if data['parent_name'] == append_data['form_name'] and data['parent_id'] == append_data['form_id']:
							append_data['child'] =data['form_name']
							if data['is_formset'] =="True":
								if data['form_name'] not in append_data:
									append_data[data['form_name']] = [] 
								append_data[data['form_name']].append(data)
							else:
								append_data[data['form_name']] = data
							
							#append_data[data['form_name']] = data
							del cleaned_data[i]
							break
							
						elif 'child' in append_data:
							child1 = append_data['child']
							if isinstance(append_data[child1],list):
								print child1 + " is a list"
								
								for child_data in append_data[child1]:

									if data['parent_name'] == child_data['form_name'] and data['parent_id'] == child_data['form_id']:			
										child_data['child'] =data['form_name']
										if data['is_formset'] =="True":
											if data['form_name'] not in child_data:
												child_data[data['form_name']] = [] 
											child_data[data['form_name']].append(data)
										else:
											child_data[data['form_name']] = data
										
										del cleaned_data[i]
										break
									elif 'child' in child_data:
										child2 = child_data['child']
										if isinstance(child_data[child2],list):
											print child2 + " is a list"
											for child_data_1 in child_data[child2]:
											
												if data['parent_name'] == child_data_1['form_name'] and data['parent_id'] == child_data_1['form_id']:
													
													child_data_1['child'] =data['form_name']
													if data['is_formset'] =="True":
														if data['form_name'] not in child_data_1:
															child_data_1[data['form_name']] = [] 
														child_data_1[data['form_name']].append(data)
													else:
														child_data_1[data['form_name']] = data
													
													del cleaned_data[i]
													break
												elif 'child' in child_data_1:
													child3 = child_data_1['child']
													if isinstance(child_data_1[child3],list):
														print child3 + " is a list"
														for child_data_2 in child_data_1[child3]:
														
															if data['parent_name'] == child_data_2['form_name'] and data['parent_id'] == child_data_1['form_id']:
																
																child_data_2['child'] =data['form_name']
																if data['is_formset'] =="True":
																	if data['form_name'] not in child_data_2:
																		child_data_2[data['form_name']] = [] 
																	child_data_2[data['form_name']].append(data)
																else:
																	child_data_2[data['form_name']] = data
																
																del cleaned_data[i]
																break
													elif isinstance(child_data[child2],dict):
														if data['parent_name'] == child_data_1[child3]['form_name'] and data['parent_id'] == append_data[child1]['form_id']:
															#print "match!" + child1
															child_data_1[child3][data['form_name']] = data	
															child_data_1[child3]['child'] = data['form_name']
															
															del cleaned_data[i]
															break	
										elif isinstance(child_data[child2],dict):
											if data['parent_name'] == append_data[child1]['form_name'] and data['parent_id'] == append_data[child1]['form_id']:
												#print "match!" + child1
												child_data[child2][data['form_name']] = data	
												child_data[child2]['child'] = data['form_name']
												
												del cleaned_data[i]
												break	
																						


							elif isinstance(append_data[child1],dict):
								print child1 +" is a dict"

								if data['parent_name'] == append_data[child1]['form_name'] and data['parent_id'] == append_data[child1]['form_id']:

templates/dynaform/file.html
{%extends 'base.html'%}
    
{% block content %}
    <h5>Your file is below</h5>
    <a href="{{ MEDIA_URL }}documents/{{ filename }}">Download File</a> 

    <p> file name = {{ filename }}</p>
{% endblock %}

templates/dynaform/legal_template_form.html
{%extends 'base.html'%}
    {% if documents %}
        <ul>
        {% for document in documents %}
            <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No documents.</p>
    {% endif %}
{% block content %}
    <h5>Upload the template you want to use.</h5>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Upload now">
    </form>

{% endblock %}

templates/dynaform/questionaire.html
{%extends 'base.html'%}

{% block content %}
    <h5>Questionaire to create the document</h5>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
		    <div class="fieldWrapper">
		        {{ field.errors }}
		        {{ field.label_tag }} {{ field }}
		        {% if field.help_text %}
		        <p class="help">{{ field.help_text|safe }}</p>
		        {% endif %}
		    </div>
		{% endfor %}
		<input type="submit" value="Create Comment">
    </form>

{% endblock %}

templates/dynaform/questionaire_v1.html
{%extends 'base.html'%}
{% load staticfiles %}

{% block content %}
	<script type="text/html" id="item-template">
	<div id="item-__prefix__">
	    {{ formset.empty_form }}
	    
	</div>
	</script>
    <h5>Questionaire to create the document</h5>
	<form id="form" method="post" action="">
        {% csrf_token %}
        	
        
        
	    <div id="items-form-container">
	    	{{formset.management_form}}
	        {% for form in formset %}
				 <div class="form-item" id="item-{{ forloop.counter0 }}">
				 {{ form.id }}
				 {{ form.as_table }}
		        </div>
		    {% endfor %}
		</div>
		<a href="#" id="add-item-button" class="btn btn-info add-item">Add Item</a>		
	    <input type="submit" value="Submit and Create Doc">
	</form>
{% endblock %}


{%block javascript%}

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script href="{% static "js/underscore.js" %}"></script>
<script >
$( document ).ready(function() {
    $('.add-item').click(function(ev) {
        console.log("Clicked!")
        ev.preventDefault();
        //var count = $('#items-form-container').children().length;
        var count = $('#items-form-container').children(".form-item").size();
        console.log("count = "+ count)
        var tmplMarkup = $('#item-template').html();
        var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
        console.log(compiledTmpl)
        $('div #items-form-container').append(compiledTmpl);
        // update form count
        $('#id_form-TOTAL_FORMS').attr('value', count+1);
        console.log($('#id_form-TOTAL_FORMS').val())
    })
});
</script>


{%endblock%}
    

templates/dynaform/questionaire_v2.html
{%extends 'base.html'%}
{% load staticfiles %}

{% block content %}
	<script type="text/html" id="item-template">
	<div id="item-__prefix__">
		{% for formset in formsets %}
				
	    {{ formset.empty_form.as_p}}	    
		    	
		{% endfor %}
	</div>
	</script>
    <h5>Questionaire to create the document</h5>
	<form id="form" method="post" action="">
        {% csrf_token %}
	    <div id="items-form-container">
	    	
	    	{% for formset in formsets %}
				
		    	{{formset.management_form}}
		        
		        {% for form in formset %}
					 <div class="form-item" id="item-{{ forloop.counter0 }}">
					 {{ form.id }}
					 {{ form.as_table }}
			        </div>
			    {% endfor %}
		    {% endfor %}
		</div>
		<a href="#" id="add-item-button" class="btn btn-info add-item">Add Item</a>		
	    <input type="submit" value="Submit and Create Doc">
	</form>
{% endblock %}


{%block javascript%}

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script href="{% static "js/underscore.js" %}"></script>
<script >
$( document ).ready(function() {
    $('.add-item').click(function(ev) {
        console.log("Clicked!")
        ev.preventDefault();
        //var count = $('#items-form-container').children().length;
        var count = $('#items-form-container').children(".form-item").size();
        console.log("count = "+ count)
        var tmplMarkup = $('#item-template').html();
        var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
        console.log(compiledTmpl)
        $('div #items-form-container').append(compiledTmpl);
        // update form count
        $('#id_form-TOTAL_FORMS').attr('value', count+1);
    })
});
</script>


{%endblock%}